### ISSUE TITLE
On ios, after receiving a call, there is no activation of the audio session.

### ISSUE THREAD

**Issue by olegys** [hiennguyen92/flutter_callkit_incoming#4]
Greetings @hiennguyen92  !  :)
I have a problem, after accepting a call through FlutterCallkitIncoming.showCallkitIncoming, I open the call screen, but there is no sound in my webrtc connection :(

I suspect that this is due to the fact that the audio session is not activated.

(if you take a call directly without your plugin, then the sound works well)

**Comment by hiennguyen92** [comment]
@olegys Hi

I just got a commit to fix it. however, I have not tested it yet.

you can test it with: 

`dependencies:
   flutter_callkit_incoming:
     git: git@github.com:hiennguyen92/flutter_callkit_incoming.git`

thanks

**Comment by olegys** [comment]
@hiennguyen92 
thanks for the quick reply) I will try to test it now)

**Comment by olegys** [comment]
A quick test showed that this works great in all cases)

1. When the application is open and we receive a call
2. When the application is minimized and we receive a call
3. When we click on the notification, the call screen will open and we accept the call
4. When the application is open or minimized on the locked screen, we receive a call and it works well

I will test it additionally on the weekend and give you detailed information if something goes wrong)

Tested on iPhone 7
IOS version 15.1

Thank you very much for your work in developing this plugin)

**Comment by olegys** [comment]
There is one incomprehensible moment
And I don't know how to reproduce it yet (
I rejected the call several times and then the notification stopped appearing, only the sound and the camera icon near the time

**Comment by olegys** [comment]
Restarting the phone solved the problem, but the previous problem returned (

**Comment by olegys** [comment]
I noticed another problem.
When I press the mute button, the application crashes.

![photo_2021-11-13_11-23-17](https://user-images.githubusercontent.com/18525409/141613584-f55e31c6-2e49-4501-912e-40a015d6b81f.jpg)

![photo_2021-11-13_11-23-13](https://user-images.githubusercontent.com/18525409/141613587-14ff6ac2-25d4-4dfd-8e80-ab198c2b8f98.jpg)

**Comment by hiennguyen92** [comment]
Ok, let me check it.

**Comment by olegys** [comment]
@hiennguyen92 Greetings!  Any news on this?)

**Comment by hiennguyen92** [comment]
Hi @olegys 
I just updated version 1.0.0+4

Fixed issue: audio session(However, I haven't been able to test it yet), can you help me check it? please.
Also the issue of crashing when mute and hold has been fixed.

**Comment by olegys** [comment]
Hi @hiennguyen92 !
Also the issue of crashing when mute and hold has been fixed. 
--- I tested turning the microphone on and off, now it works well and does not cause the call to fail)

audio session(However, I haven't been able to test it yet) 
--- I tested this part too and identified some steps:
1. When I receive a call via FlutterCallkitIncoming.showCallkitIncoming, I still have no sound in my webrtc connection
2. But when I receive a call directly without FlutterCallkitIncoming.showCallkitIncoming, the sound works and the IOS shows the microphone setting in the status bar for a few seconds (see screenshot)
3. After these steps, I will now try to make a call through FlutterCallkitIncoming.showCallkitIncoming, then the sound will also work fine
4. Therefore, for the call to start working normally, I need to accept it for the first time without FlutterCallkitIncoming.showCallkitIncoming, and then all the next calls will work fine with FlutterCallkitIncoming.showCallkitIncoming and Ios will show the activation of the microphone in the status bar

I found some answers on the Internet, maybe they will help solve the problem
There advise:
1. You'll need to wait for the didActivateAudioSession event to fire before actually accepting the call, otherwise your library may fail to get control over the audio. (https://issueexplorer.com/issue/react-native-webrtc/react-native-callkit/57)

2.  try sharedSession.setCategory(AVAudioSessionCategoryPlayAndRecord) try sharedSession.setMode(AVAudioSessionModeVoiceChat) (https://stackoverflow.com/questions/55391026/no-sound-after-connecting-to-webrtc-when-app-is-launched-in-background-using-pus)

3. Did you make sure to configure your audio session (i.e. set its category to PlayAndRecord and its mode to VoiceChat or VideoChat) before you answer or start a call? (https://developer.apple.com/forums/thread/64544)

**Comment by hiennguyen92** [comment]
@olegys thanks you.
I will build a webrtc and do a demo about it. I will check and test it.

**Comment by olegys** [comment]
Hey! @hiennguyen92 
Maybe I can help test this?)

**Comment by olegys** [comment]
@hiennguyen92 Hi!
Any news about this?

**Comment by hiennguyen92** [comment]
Hi @olegys sorry for late.

I just fixed it at version 1.0.0+5

**Comment by olegys** [comment]
> Hi @olegys sorry for late.
> 
> I just fixed it at version 1.0.0+5

Hi @hiennguyen92, thanks !
Do I need to make any changes to the code?
Version 1.0.0 + 5 still doesn't work for me (

**Comment by hiennguyen92** [comment]
Hi @olegys, any error?

**Comment by olegys** [comment]
> Hi @olegys, toi tested and it worked fine the first time.

There are no errors, there is simply no sound in webrtc after receiving a call.

**Comment by hiennguyen92** [comment]
https://gist.github.com/hiennguyen92/82ab1e0e9a3237baca5ec4e16399a4f3

I have a simple implementation here. I'm not sure if it has flaws.
i use example `flutter-webrtc-demo`

**Comment by olegys** [comment]
@hiennguyen92 Thanks!  Perhaps the problem is that I am not on the same screen, I redirect the user to the call screen after accepting it.  And it turns out that webrtc is initialized only after receiving the call.

**Comment by olegys** [comment]
@hiennguyen92 Hi!

Solved the problem with a temporary fix)

It turns out that CallKit audio conflicts with:

     final MediaStream stream = await navigator.mediaDevices.getUserMedia (
       mediaConstraints,
     );

And in order to have sound, you need to create a stream before accepting the call and then transfer it to the call page.

final MediaStream stream = await _createStream ();

**Comment by hiennguyen92** [comment]
@olegys thank you very much. I will also re-investigate this issue.

**Comment by olegys** [comment]
> 

And thank you for the work done and the great plugin! )

**Comment by olegys** [comment]
> @olegys thank you very much. I will also re-investigate this issue.

And thank you for the work done and the great plugin! )

**Comment by 488taimoor** [comment]
No Audio. when I accept call from voipPush callkit.  

`Error Domain=NSOSStatusErrorDomain Code=561017449 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}`

my AppDelegate.swift file 
`import UIKit
import CallKit
import AVFAudio
import PushKit
import Flutter
import flutter_callkit_incoming
import WebRTC

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate, PKPushRegistryDelegate, CallkitIncomingAppDelegate {

    
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        //Setup VOIP
        let mainQueue = DispatchQueue.main
        let voipRegistry: PKPushRegistry = PKPushRegistry(queue: mainQueue)
        voipRegistry.delegate = self
        voipRegistry.desiredPushTypes = [PKPushType.voIP]

        //Use if using WebRTC
        
        RTCAudioSession.sharedInstance().useManualAudio = true
        RTCAudioSession.sharedInstance().isAudioEnabled = false
        
//        setupAudioSession()
       
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    func setupAudioSession() {
        let audioSession = RTCAudioSession.sharedInstance()

        // Lock the audio session configuration
        audioSession.lockForConfiguration()

        do {
            // Set the audio session category and mode
            try audioSession.setCategory(.playAndRecord, mode: .voiceChat, options: [.allowBluetooth, .defaultToSpeaker])
            // Activate the audio session
            try audioSession.setActive(true)
            print("Audio session activated successfully.")
        } catch {
            print("Error activating audio session: \(error.localizedDescription)")
        };
            // Always unlock the audio session configuration
            audioSession.unlockForConfiguration()
        
    }
    
    // Call back from Recent history
    override func application(_ application: UIApplication,
                              continue userActivity: NSUserActivity,
                              restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        
        guard let handleObj = userActivity.handle else {
            return false
        }
        
        guard let isVideo = userActivity.isVideo else {
            return false
        }
        let objData = handleObj.getDecryptHandle()
        let nameCaller = objData["nameCaller"] as? String ?? ""
        let handle = objData["handle"] as? String ?? ""
        let data = flutter_callkit_incoming.Data(id: UUID().uuidString, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0, duration: 60000)
        //set more data...
        //data.nameCaller = nameCaller
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.startCall(data, fromPushKit: true)
        
        return super.application(application, continue: userActivity, restorationHandler: restorationHandler)
    }
    
    // Handle updated push credentials
    func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, for type: PKPushType) {
        print(credentials.token)
        let deviceToken = credentials.token.map { String(format: "%02x", $0) }.joined()
        print(deviceToken)
        //Save deviceToken to your server
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP(deviceToken)
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
        print("didInvalidatePushTokenFor")
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP("")
    }
    
    // Handle incoming pushes
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        print("didReceiveIncomingPushWith")
        guard type == .voIP else { return }
        
        let id = payload.dictionaryPayload["id"] as? String ?? ""
        let nameCaller = payload.dictionaryPayload["nameCaller"] as? String ?? ""
        let handle = payload.dictionaryPayload["handle"] as? String ?? ""
        let isVideo = payload.dictionaryPayload["isVideo"] as? Bool ?? false
        
        let data = flutter_callkit_incoming.Data(id: id, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0, duration: 60000)
        //set more data
        data.extra = ["user": "abc@123", "platform": "ios"]
        //data.iconName = ...
        //data.....
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(data, fromPushKit: true)
        
        //Make sure call completion()
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            completion()
        }
    }
    
    
    // Func Call api for Accept
    func onAccept(_ call: Call, _ action: CXAnswerCallAction) {
        let json = ["action": "ACCEPT", "data": call.data.toJSON()] as [String: Any]
        print("LOG: onAccept")
        
        self.performRequest(parameters: json) { result in
            switch result {
            case .success(let data):
                print("Received data: \(data)")
                //Make sure call action.fulfill() when you are done(connected WebRTC - Start counting seconds)
                action.fulfill()

            case .failure(let error):
                print("Error: \(error.localizedDescription)")
            }
        }
    }
    
    // Func Call API for Decline
    func onDecline(_ call: Call, _ action: CXEndCallAction) {
        let json = ["action": "DECLINE", "data": call.data.toJSON()] as [String: Any]
        print("LOG: onDecline")
        self.performRequest(parameters: json) { result in
            switch result {
            case .success(let data):
                print("Received data: \(data)")
                //Make sure call action.fulfill() when you are done
                action.fulfill()

            case .failure(let error):
                print("Error: \(error.localizedDescription)")
            }
        }
    }
    
    // Func Call API for End
    func onEnd(_ call: Call, _ action: CXEndCallAction) {
        let json = ["action": "END", "data": call.data.toJSON()] as [String: Any]
        print("LOG: onEnd")
        self.performRequest(parameters: json) { result in
            switch result {
            case .success(let data):
                print("Received data: \(data)")
                //Make sure call action.fulfill() when you are done
                action.fulfill()

            case .failure(let error):
                print("Error: \(error.localizedDescription)")
            }
        }
    }
    
    // Func Call API for TimeOut
    func onTimeOut(_ call: Call) {
        let json = ["action": "TIMEOUT", "data": call.data.toJSON()] as [String: Any]
        print("LOG: onTimeOut")
        self.performRequest(parameters: json) { result in
            switch result {
            case .success(let data):
                print("Received data: \(data)")

            case .failure(let error):
                print("Error: \(error.localizedDescription)")
            }
        }
    }
    
    // Func Callback Toggle Audio Session
    func didActivateAudioSession(_ audioSession: AVAudioSession) {
        //Use if using WebRTC
        RTCAudioSession.sharedInstance().audioSessionDidActivate(audioSession)
        RTCAudioSession.sharedInstance().isAudioEnabled = true
    }
    
    // Func Callback Toggle Audio Session
    func didDeactivateAudioSession(_ audioSession: AVAudioSession) {
        //Use if using WebRTC
        RTCAudioSession.sharedInstance().audioSessionDidDeactivate(audioSession)
        RTCAudioSession.sharedInstance().isAudioEnabled = false
    }
    
    func performRequest(parameters: [String: Any], completion: @escaping (Result<Any, Error>) -> Void) {
        if let url = URL(string: "https://webhook.site/e32a591f-0d17-469d-a70d-33e9f9d60727") {
            var request = URLRequest(url: url)
            request.httpMethod = "POST"
            request.addValue("application/json", forHTTPHeaderField: "Content-Type")
            //Add header
            
            do {
                let jsonData = try JSONSerialization.data(withJSONObject: parameters, options: [])
                request.httpBody = jsonData
            } catch {
                completion(.failure(error))
                return
            }
            
            let task = URLSession.shared.dataTask(with: request) { (data, response, error) in
                if let error = error {
                    completion(.failure(error))
                    return
                }
                
                guard let data = data else {
                    completion(.failure(NSError(domain: "mobile.app", code: 0, userInfo: [NSLocalizedDescriptionKey: "Empty data"])))
                    return
                }

                do {
                    let jsonObject = try JSONSerialization.jsonObject(with: data, options: [])
                    completion(.success(jsonObject))
                } catch {
                    completion(.failure(error))
                }
            }
            task.resume()
        } else {
            completion(.failure(NSError(domain: "mobile.app", code: 0, userInfo: [NSLocalizedDescriptionKey: "Invalid URL"])))
        }
    }
    
    
}
`
@hiennguyen92 any solution?

**Comment by hamada-developer** [comment]
@488taimoor 
Same issue

**Comment by AB0s** [comment]
Same error:Error Domain=NSOSStatusErrorDomain Code=561017449 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}
Any updates?

**Comment by AB0s** [comment]
Same error:Error Domain=NSOSStatusErrorDomain Code=561017449 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}
Any updates?
@hiennguyen92

**Comment by AB0s** [comment]
> > Та же ошибка: Error Domain=NSOSStatusErrorDomain Code=561017449 «Не удалось активировать сеанс» UserInfo={NSLocalizedDescription=Не удалось активировать сеанс} Есть какие-нибудь обновления? [@hiennguyen92](https://github.com/hiennguyen92)
> 
> Привет, удалось решить ошибку? А то я тоже пробовал и через AppDelegate реализовать работу с CallKit, и через flutter_callkit_incoming - почти всегда аудио сессия падает


I forgot how I resolved but try to add action.fulfill before switch checking: 
```
func onAccept(_ call: Call, _ action: CXAnswerCallAction) {
    let json = ["action": "ACCEPT", "data": call.data.toJSON()] as [String: Any]
    print("LOG: onAccept")

    // ✅ СРАЗУ вызываем fulfill для быстрой активации CallKit
    action.fulfill()

    // API запрос делаем в фоне
    self.performRequest(parameters: json) { result in
        switch result {
        case .success(let data):
            print("Received data: \(data)")
            // action.fulfill() уже вызван выше
        case .failure(let error):
            print("Error: \(error.localizedDescription)")
            // action.fulfill() уже вызван выше
        }
```
