### ISSUE TITLE
"Accept" button at fullscreen incoming call does not open app, when app is in background or terminate

### ISSUE THREAD

**Issue by hieplee2997** [hiennguyen92/flutter_callkit_incoming#69]
I have flutter a web-rtc app, i want to use firebase notification so i use this package. I just want to handle onAccept and onDecline event to switch to my call screen. But i have some problem.

Accept button on top screen notify still open app normal, but when i click it at fullscreen view, it terminate app although app is running in background. 

My params: 
``` var params = <String, dynamic>{
      'id': "5c3ab1f0-8750-42eb-8d29-ad28e3d7f336",
      'nameCaller': 'Hiep sssssssLee',
      'appName': 'PancakeChat',
      'avatar': 'https://i.pravatar.cc/100',
      'handle': '0123456789',
      'type': 1,
      'duration': 30000,
      'android': <String, dynamic>{
        'isCustomNotification': true,
        'isShowLogo': false,
        'isShowCallback': false,
        'ringtonePath': 'incoming_sound',
        'backgroundColor': '#0955fa',
        'background': 'https://i.pravatar.cc/500',
        'actionColor': '#4CAF50'
      },
      'ios': <String, dynamic>{
        'iconName': 'CallKitLogo',
        'handleType': '',
        'supportsVideo': true,
        'audioSessionMode': 'default',
        'audioSessionActive': true,
        'audioSessionPreferredSampleRate': 44100.0,
        'audioSessionPreferredIOBufferDuration': 0.005,
        'supportsDTMF': true,
        'supportsHolding': true,
        'supportsGrouping': false,
        'supportsUngrouping': false,
        'ringtonePath': 'incoming_sound'
      }
    };
    await FlutterCallkitIncoming.showCallkitIncoming(params);
```
It is a bug or i use it wrong. Thanks

**Comment by mdusko** [comment]
Hello, the same behavior if the phone is locked.

https://user-images.githubusercontent.com/65610208/159962828-b982a2c6-9f65-4081-94dc-fc895a042758.mov

**Comment by hiennguyen92** [comment]
I will double check it.

**Comment by 1AhmedYasser** [comment]
any updates regarding this issue ? @hiennguyen92

**Comment by faisalmushtaq007** [comment]
i am having same issue, please look into it. Its a huge problem

**Comment by faisalmushtaq007** [comment]
@1AhmedYasser have you found any solution??

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 I will deploy version fix it tonight

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 Sir can you please attach an example here as how to navigate on event ACCEPT

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 I just updated version 1.0.1+6, this issue has been fixed.

**Comment by hieplee2997** [comment]
@hiennguyen92 sorry i comment in other issue, it still an error in android. In full screen notification, if i press "Decline" button then app will be killed even though it's running. Is it error? Can you fix it. Thanks

**Comment by hiennguyen92** [comment]
Ok. Let me check

**Comment by works-tabei** [comment]
@hiennguyen92  i have same issue app in backgroud.
I investigated this issuse.
I  changed  onAcceptClick of CallkitIncomingActivity  from intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) to intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK  or Intent.FLAG_ACTIVITY_CLEAR_TASK).
as result solved issue.

**Comment by hiennguyen92** [comment]
@works-tabei thank you

**Comment by hiennguyen92** [comment]
@hieplee2997 @works-tabei @faisalmushtaq007 @1AhmedYasser  I just updated version 1.0.1+7 please try again.

**Comment by zionnite** [comment]
> @hiennguyen92 i have same issue app in backgroud. I investigated this issuse. I changed onAcceptClick of CallkitIncomingActivity from intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) to intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK). as result solved issue.

as at today, am still having same issue, am using version version 1.0.1+7

**Comment by hieplee2997** [comment]
@hiennguyen92 seem 1.0.1+7 more wrong behavior. My app restart when tap on Accept button. Can you check again?
Anyway thank you for support

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.

**Comment by hiennguyen92** [comment]
you can try new version 1.0.2

**Comment by zionnite** [comment]
according to my finding, the new version 1.0.2 does open the app but the `ACTION_CALL_ENDED` AND  `ACTION_CALL_ACCEPT` are never fired
